[package]
name = "hislab"
version = "0.2.0"
edition = "2024"
authors = ["Joshua"]
description = "A high-performance slab allocator with hierarchical bitmap for O(1) insert/remove operations"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JoshuaBOUCHAT/hislab"
documentation = "https://docs.rs/hislab"
readme = "README.md"
keywords = ["slab", "allocator", "bitmap", "simd", "data-structure"]
categories = ["data-structures", "memory-management"]


[dependencies]
libc = "0.2"
memmap2 = "0.9.10"
rand = { version = "0.8", optional = true }

[features]
default = []
rand = ["dep:rand"]

[profile.release]
lto = true
codegen-units = 1
